VIA_ENABLE = yes
LTO_ENABLE = yes

RGB_MATRIX_ENABLE  = yes
RGBLIGHT_ENABLE    = no
MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = no
OLED_ENABLE        = no
SLEEP_LED_ENABLE   = no
WPM_ENABLE         = no


#Dont use
CONSOLE_ENABLE     = no
MOUSEKEY_ENABLE    = no
BOOTMAGIC_ENABLE   = no
COMBO_ENABLE	   = no
AUDIO_ENABLE	   = no
MIDI_ENABLE		   = no
BLUETOOTH_ENABLE   = no